
package py.gov.senatics.ws.prueba;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-11-30T09:32:15.357-03:00
 * Generated source version: 2.4.6
 */

@WebFault(name = "RegistroIdentificacionesException", targetNamespace = "http://identificaciones.ws.sii.senatics.gov.py/")
public class RegistroIdentificacionesException_Exception extends Exception {
    
    private py.gov.senatics.ws.prueba.RegistroIdentificacionesException registroIdentificacionesException;

    public RegistroIdentificacionesException_Exception() {
        super();
    }
    
    public RegistroIdentificacionesException_Exception(String message) {
        super(message);
    }
    
    public RegistroIdentificacionesException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public RegistroIdentificacionesException_Exception(String message, py.gov.senatics.ws.prueba.RegistroIdentificacionesException registroIdentificacionesException) {
        super(message);
        this.registroIdentificacionesException = registroIdentificacionesException;
    }

    public RegistroIdentificacionesException_Exception(String message, py.gov.senatics.ws.prueba.RegistroIdentificacionesException registroIdentificacionesException, Throwable cause) {
        super(message, cause);
        this.registroIdentificacionesException = registroIdentificacionesException;
    }

    public py.gov.senatics.ws.prueba.RegistroIdentificacionesException getFaultInfo() {
        return this.registroIdentificacionesException;
    }
}
